name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.22.2
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22.2
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Test
      run: go test -v ./...